service: pollenow-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI, ''}
    DB_NAME: ${env:DB_NAME, ''}
    JWT_SECRET: ${env:JWT_SECRET, ''}
    GOOGLE_MAPS_API_KEY: ${env:GOOGLE_MAPS_API_KEY, ''}


plugins:
  - serverless-offline

functions:
  register:
    handler: src/handlers/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: 
            origin: 'http://localhost:5173' 
            headers:
              - Content-Type
              - Authorization
  login:
    handler: src/handlers/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization
  logout:
    handler: src/handlers/auth/logout.handler
    events:
      - http:
          path: auth/logout
          method: post
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization

  refreshToken:
    handler: src/handlers/auth/refreshToken.handler
    events:
      - http:
          path: auth/refresh-token
          method: post
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization

  protected:
    handler: src/handlers/protected.handler
    events:
      - http:
          path: protected
          method: get
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization 
  
  # Location endpoints - one location per user
  saveLocation:
    handler: src/handlers/location/saveLocation.handler
    events:
      - http:
          path: location
          method: post
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization
  getLocation:
    handler: src/handlers/location/getLocation.handler
    events:
      - http:
          path: location
          method: get
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization
  deleteLocation:
    handler: src/handlers/location/deleteLocation.handler
    events:
      - http:
          path: location
          method: delete
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization
              
  # Pollen endpoints
  getPollenForecast:
    handler: src/handlers/pollen/getPollenForecast.handler
    events:
      - http:
          path: pollen/forecast
          method: get
          cors: 
            origin: 'http://localhost:5173'
            headers:
              - Content-Type
              - Authorization
            
custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true