service: pollenow-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI, ''}
    DB_NAME: ${env:DB_NAME, ''}
    JWT_SECRET: ${env:JWT_SECRET, ''}

plugins:
  - serverless-offline

functions:
  register:
    handler: src/handlers/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true
  login:
    handler: src/handlers/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
  logout:
    handler: src/handlers/auth/logout.handler
    events:
      - http:
          path: auth/logout
          method: post
          cors: true

  refreshToken:
    handler: src/handlers/auth/refreshToken.handler
    events:
      - http:
          path: auth/refresh-token
          method: post
          cors: true
  protected:
    handler: src/handlers/protected.handler
    events:
      - http:
          path: protected
          method: get
          cors: true
          
custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true